# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cligpt < Formula
  desc "-| Oh, cligpt is your reliable research assistant. Just type in your questions and queries, and it will provide instant answers based on a vast knowledge base. No matter what you want to know, cligpt is ready to help, making your research easier and more efficient than ever."
  homepage "https://github.com/maxwelbm/cligpt"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/maxwelbm/cligpt/releases/download/v0.1.0/cligpt_Darwin_arm64.tar.gz"
      sha256 "96f5a0466604cec710a94436fe5a59cb242f0905754c6cc7b1404ac81ebc96f6"

      def install
        bin.install "cligpt"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/maxwelbm/cligpt/releases/download/v0.1.0/cligpt_Darwin_x86_64.tar.gz"
      sha256 "39e232808272e4219d9a8492fb274b13f5b124e03c3291056002a0eb8fbe84ab"

      def install
        bin.install "cligpt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/maxwelbm/cligpt/releases/download/v0.1.0/cligpt_Linux_arm64.tar.gz"
      sha256 "b487bbb5dfc821c78ca85c3bc57d9c5feee53dd5e7f3fac7d8efbc196f76918b"

      def install
        bin.install "cligpt"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/maxwelbm/cligpt/releases/download/v0.1.0/cligpt_Linux_x86_64.tar.gz"
      sha256 "9ef20161a7b426fef4513d38a8a681ce200b45555b1195c6138edebad1e3bfdc"

      def install
        bin.install "cligpt"
      end
    end
  end

  test do
    system "#{bin}/cligpt"
  end
end
