# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "../custom_download_strategy"
class Exp < Formula
  desc "A simple go project"
  homepage "https://github.com/maxwelbm/exp"
  version "0.1.3"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/maxwelbm/exp/releases/download/v0.1.3/exp_Darwin_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "1992959078dfa9d6f43d5cf421b9828ece3d074eac5b682e5bc95bf9e7ce4208"

      def install
        bin.install "exp"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/maxwelbm/exp/releases/download/v0.1.3/exp_Darwin_x86_64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "b50d59a3bfd6e65ef62fc26ca553908910737d1b69874e252a5f4abc015a6e7f"

      def install
        bin.install "exp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/maxwelbm/exp/releases/download/v0.1.3/exp_Linux_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "a14b6ff2d53f6fa60964e56d15ffb0c7c1c79eb69e01f021e83d23493eefd847"

      def install
        bin.install "exp"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/maxwelbm/exp/releases/download/v0.1.3/exp_Linux_x86_64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "0214589bb59b79d7efebee711b9e26dee5bea924963b65875756bdde6dcdfba6"

      def install
        bin.install "exp"
      end
    end
  end

  test do
    system "#{bin}/exp"
  end
end
