# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Exp < Formula
  desc "A simple go project experients"
  homepage "https://github.com/maxwelbm/exp"
  version "0.1.4"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/maxwelbm/exp/releases/download/v0.1.4/exp_Darwin_arm64.tar.gz"
      sha256 "8bb9699ce537406c5fe3ae13773b7afe1af9ecbd6c59620d6ca4b0e676a5075c"

      def install
        bin.install "exp"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/maxwelbm/exp/releases/download/v0.1.4/exp_Darwin_x86_64.tar.gz"
      sha256 "8da3d6e37d3a3e0365c988b1bfb4ac4370b59193d67c7b0cb2fe09ffe59c79a0"

      def install
        bin.install "exp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/maxwelbm/exp/releases/download/v0.1.4/exp_Linux_arm64.tar.gz"
      sha256 "59976b10533d825436e5c86ebf5747e9ea39adc5b19c1d427dedca2403cb32b3"

      def install
        bin.install "exp"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/maxwelbm/exp/releases/download/v0.1.4/exp_Linux_x86_64.tar.gz"
      sha256 "9bd09a76354af07da3c18c8fe6db1d29a97f31646d8f5db3214b57d26ea22a25"

      def install
        bin.install "exp"
      end
    end
  end

  test do
    system "#{bin}/exp"
  end
end
