# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "../custom_download_strategy"
class Maxwelbm < Formula
  desc "A simple go project"
  homepage "https://github.com/maxwelbm/exp"
  version "0.1.2"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/maxwelbm/exp/releases/download/v0.1.2/exp_Darwin_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "8dffc3177bb5204a13bb7edaf77e277aa1c5c33de735e2b6e547eb0d21242d56"

      def install
        bin.install "exp"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/maxwelbm/exp/releases/download/v0.1.2/exp_Darwin_x86_64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "ddbb8c4b126f6dbd385878e7763677c1f6b7790a99736e4b5f2fcdb19f3dfed3"

      def install
        bin.install "exp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/maxwelbm/exp/releases/download/v0.1.2/exp_Linux_x86_64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "f442169acd944e035620d77adff21f1c1d46bae8fd1f6ba713f60adaf09e5fbb"

      def install
        bin.install "exp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/maxwelbm/exp/releases/download/v0.1.2/exp_Linux_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "0f8ed45327c10d5fb2eb2d9cecfc78ff84910dc879090a92003146a264c658f8"

      def install
        bin.install "exp"
      end
    end
  end

  test do
    system "#{bin}/exp"
  end
end
